### ISSUE TITLE
Library libgeos-3.5.1.dylib not found in Python3.6

### ISSUE THREAD

**Issue by gitporst** [conda-forge/geopandas-feedstock#27]
Hi,

I'm running anaconda on a Mac OSX.
after 
`conda config --append channels conda-forge` 
and
`conda create -n tools_conda_venv python=3`
`source activate tools_conda_venv`
and
`conda install geopandas`

I get the following error

Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

```
> import geopandas
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/ottor/anaconda3/envs/tools_conda_venv/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
>     from geopandas.io.file import read_file
>   File "/Users/ottor/anaconda3/envs/tools_conda_venv/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
>     import fiona
>   File "/Users/ottor/anaconda3/envs/tools_conda_venv/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
>     from fiona.collection import Collection, BytesCollection, vsi_path
>   File "/Users/ottor/anaconda3/envs/tools_conda_venv/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
>     from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
> ImportError: dlopen(/Users/ottor/anaconda3/envs/tools_conda_venv/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libgeos-3.5.1.dylib
>   Referenced from: /Users/ottor/anaconda3/envs/tools_conda_venv/lib/libspatialite.7.dylib
>   Reason: image not found
```

There is a libgeos-3.5.0.dylib, though. How can it be fixed?

**Comment by gitporst** [comment]
`conda config --prepend channels conda-forge`
fixed the problem, I'm closing it.
