### ISSUE TITLE
Importing geopandas is leading to this error message

### ISSUE THREAD

**Issue by msaharia** [conda-forge/geopandas-feedstock#28]
```
ImportError                               Traceback (most recent call last)
<ipython-input-3-c9ee6bd24dbc> in <module>()
----> 1 import geopandas

~/anaconda3/lib/python3.6/site-packages/geopandas/__init__.py in <module>()
      2 from geopandas.geodataframe import GeoDataFrame
      3
----> 4 from geopandas.io.file import read_file
      5 from geopandas.io.sql import read_postgis
      6 from geopandas.tools import sjoin

~/anaconda3/lib/python3.6/site-packages/geopandas/io/file.py in <module>()
      1 import os
      2
----> 3 import fiona
      4 import numpy as np
      5

~/anaconda3/lib/python3.6/site-packages/fiona/__init__.py in <module>()
     67 from six import string_types
     68
---> 69 from fiona.collection import Collection, BytesCollection, vsi_path
     70 from fiona._drivers import driver_count, GDALEnv
     71 from fiona.drvsupport import supported_drivers

~/anaconda3/lib/python3.6/site-packages/fiona/collection.py in <module>()
      7
      8 from fiona import compat
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import (

ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory

```

**Comment by ocefpaf** [comment]
Please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by msaharia** [comment]
@ocefpaf My channel priority is already set to conda-forge:
```
channels:
  - conda-forge
  - defaults
```

Installation went fine `conda install -c conda-forge geopandas`. But  in the interpreter, `import geopandas` leads to this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/glade/u/home/manab/anaconda3/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```

I tried a fresh install as well.

**Comment by jorisvandenbossche** [comment]
Please show the full output of all install commands you did and of `conda list`.

> I tried a fresh install as well.

Did you try making a new clean environment? If so, please show the full output of that.

**Comment by ocefpaf** [comment]
> Did you try making a new clean environment?

That is probably the cause there. I see you are using the anaconda distro and the pre-installed packages are known to interfere with a third party channel (conda-forge). Only a clean env will work.

**Comment by ocefpaf** [comment]
@msaharia please try:

```shell
conda create --yes --name TEST python=3.6 geopandas --channel conda-forge
source activate TEST
python -c "import geopandas; print(geopandas.__version__)"
```

If that works everything is OK and the issue is the fact that you cannot mix the anaconda distribution packages with a third party channel. If not please send the results of:

```
conda list
conda info -a
```

for that `TEST` environment.

**Comment by muhark** [comment]
@ocefpaf tried your solution, got the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lunayneko/anaconda3/envs/TEST/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/home/lunayneko/anaconda3/envs/TEST/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/home/lunayneko/anaconda3/envs/TEST/lib/python3.6/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/lunayneko/anaconda3/envs/TEST/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  File "fiona/ogrext.pyx", line 35, in init fiona.ogrext
  File "/home/lunayneko/anaconda3/envs/TEST/lib/python3.6/site-packages/fiona/path.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

my output of `conda list`
```
# packages in environment at /home/lunayneko/anaconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py36_1003    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto3                     1.9.20                     py_0    conda-forge
botocore                  1.12.20                    py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2018.8.24             py36_1001    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.61.1               h74213dd_2    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
docutils                  0.14                  py36_1001    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fiona                     1.8a3            py36hb00a9d7_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4            py36hb00a9d7_9    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
geotiff                   1.4.2                h700e5ad_4    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
intel-openmp              2019.0                      118  
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.1               hbb41f41_0    conda-forge
libcurl                   7.61.1               hbdb9355_2    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgdal                   2.2.4                hbd6f514_9    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1                he6cff42_8    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libpq                     10.5                 he29860b_0    conda-forge
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a              hdfcc80b_23    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
matplotlib                2.2.3            py36h8e2386c_0    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
numpy                     1.15.0           py36h1b885b7_0  
numpy-base                1.15.0           py36h3dfced4_0  
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                10.5                 h66035e0_0    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
psycopg2                  2.7.5            py36hdffb7b8_2    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyproj                    1.9.5.1          py36h508ed2a_5    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pysal                     1.14.4.post2             py36_1    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
rtree                     0.8.3                 py36_1000    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scipy                     1.1.0            py36hc49cb51_0  
setuptools                40.4.3                   py36_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlalchemy                1.2.12           py36h470a237_0    conda-forge
sqlite                    3.25.2               hb1c47c0_0    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wheel                     0.32.1                   py36_0    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.2                h8c8a85c_6    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

my output of `conda info -a`
```

     active environment : TEST
    active env location : /home/lunayneko/anaconda3/envs/TEST
            shell level : 1
       user config file : /home/lunayneko/.condarc
 populated config files : /home/lunayneko/.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/lunayneko/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/lunayneko/anaconda3/pkgs
                          /home/lunayneko/.conda/pkgs
       envs directories : /home/lunayneko/anaconda3/envs
                          /home/lunayneko/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Linux/4.18.12-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

# conda environments:
#
base                     /home/lunayneko/anaconda3
TEST                  *  /home/lunayneko/anaconda3/envs/TEST

sys.version: 3.6.4 |Anaconda custom (64-bit)| (defaul...
sys.prefix: /home/lunayneko/anaconda3
sys.executable: /home/lunayneko/anaconda3/bin/python
conda location: /home/lunayneko/anaconda3/lib/python3.6/site-packages/conda
conda-build: /home/lunayneko/anaconda3/bin/conda-build
conda-convert: /home/lunayneko/anaconda3/bin/conda-convert
conda-develop: /home/lunayneko/anaconda3/bin/conda-develop
conda-env: /home/lunayneko/anaconda3/bin/conda-env
conda-index: /home/lunayneko/anaconda3/bin/conda-index
conda-inspect: /home/lunayneko/anaconda3/bin/conda-inspect
conda-metapackage: /home/lunayneko/anaconda3/bin/conda-metapackage
conda-render: /home/lunayneko/anaconda3/bin/conda-render
conda-server: /home/lunayneko/anaconda3/bin/conda-server
conda-skeleton: /home/lunayneko/anaconda3/bin/conda-skeleton
conda-verify: /home/lunayneko/anaconda3/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: TEST
CONDA_EXE: /home/lunayneko/anaconda3/bin/conda
CONDA_PREFIX: /home/lunayneko/anaconda3/envs/TEST
CONDA_PROMPT_MODIFIER: (TEST) 
CONDA_PYTHON_EXE: /home/lunayneko/anaconda3/bin/python
CONDA_ROOT: /home/lunayneko/anaconda3
CONDA_SHLVL: 1
MODULEPATH: /etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
PATH: /home/lunayneko/anaconda3/envs/TEST/bin:/home/lunayneko/anaconda3/bin:/home/lunayneko/anaconda3/bin:/home/lunayneko/anaconda3/bin:/home/lunayneko/anaconda3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/lunayneko/.local/bin:/home/lunayneko/bin
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>


WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by ocefpaf** [comment]
@muhark for some odd reason the dev releases leaked in the `main` channel. That should be solved now.
