### ISSUE TITLE
Import Error on libnsl.so.1 on a clean environment.

### ISSUE THREAD

**Issue by green2jello** [conda-forge/geopandas-feedstock#69]
Issue: Cannot import geopandas on a clean environment install.

I tried using the following code based on previous issues I've seen here to attempt to get geopandas to install:
```
$ conda create -n test
$ conda activate test
$ conda install -c conda-forge geopandas
$ python -c "import; print(geopandas.\_\_version\_\_)
```
and received the following error back:
```
File "<string>", line 1
    install geopandas; print(geopandas.__version__)
            ^
SyntaxError: invalid syntax
(test) [steve@localhost ~]$ python -c "import geopandas; print(geopandas.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/steve/anaconda3/envs/test/lib/python3.8/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file  # noqa
  File "/home/steve/anaconda3/envs/test/lib/python3.8/site-packages/geopandas/io/file.py", line 6, in <module>
    import fiona
  File "/home/steve/anaconda3/envs/test/lib/python3.8/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/steve/anaconda3/envs/test/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

My conda list, and .condarc are below. Am I missing a simple step? Or is this more of a fiona issue?

Thanks so much for any help that can be provided.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/steve/anaconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py38_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fiona                     1.8.11           py38h900e953_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.2            py38hbb6b9fb_2    conda-forge
geopandas                 0.6.1                      py_1    conda-forge
geos                      3.7.2                he1b5a44_2    conda-forge
geotiff                   1.5.1                h32362d2_6    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgdal                   3.0.2                hc7cfd23_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.1           nompi_h94020b1_101    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_2    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h4f6d029_1032    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.3           py38h95a1406_0    conda-forge
openjpeg                  2.3.1                h21c5421_1    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    0.25.3           py38hb3f55d8_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pip                       19.3.1                   py38_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_2    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyproj                    2.4.1            py38h12732c1_1    conda-forge
python                    3.8.0                h357f687_3    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rtree                     0.8.3           py38h7b0cdae_1003    conda-forge
setuptools                41.6.0                   py38_1    conda-forge
shapely                   1.6.4           py38hec07ddf_1006    conda-forge
six                       1.13.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.6.2                h7d710e0_2    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
wheel                     0.33.6                   py38_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code>, <code>.condarc</code>, and system ( <code>conda info</code> ):
<details>

```
$ cat ~/.condarc
channel_priority: strict
channels:
  - conda-forge
  - defaults
```
OS info: CentOS 8 on Oracle VM Virtualbox.
```
$ conda info

     active environment : base
    active env location : /home/steve/anaconda3
            shell level : 1
       user config file : /home/steve/.condarc
 populated config files : /home/steve/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : 
       base environment : /home/steve/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/steve/anaconda3/pkgs
                          /home/steve/.conda/pkgs
       envs directories : /home/steve/anaconda3/envs
                          /home/steve/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.18.0-80.11.2.el8_0.x86_64 centos/8.0.1905 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by jorisvandenbossche** [comment]
It's indeed a fiona (or rather gdal) issue. But your environment looks good (only gcc from defaults, that's expected).
