### ISSUE TITLE
Unable to install geopandas on Windows 10

### ISSUE THREAD

**Issue by AlexJew** [conda-forge/geopandas-feedstock#80]
I am unable to install `geopandas` from `conda-forge` on Windows 10 64-bit. However, when installing from `anaconda`, the installation is successful.  

<br/>
Environment (<code>conda list
</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\jewell\Anaconda3\envs\thermal_comfort:
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : thermal_comfort
    active env location : C:\Users\jewell\Anaconda3\envs\thermal_comfort
            shell level : 2
       user config file : C:\Users\jewell\.condarc
 populated config files : C:\Users\jewell\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\jewell\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\jewell\Anaconda3\pkgs
                          C:\Users\jewell\.conda\pkgs
                          C:\Users\jewell\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jewell\Anaconda3\envs
                          C:\Users\jewell\.conda\envs
                          C:\Users\jewell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

<br/>
Environment (<code>conda config --show
</code>):
<details>

```
(thermal_comfort) C:\Users\jewell>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: True
bld_path:
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: strict
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: C:\Users\jewell\Anaconda3\conda-bld
custom_channels:
  conda-forge: https://conda.anaconda.org
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults:
    - https://conda.anaconda.org/conda-forge
  local:
debug: False
default_channels:
  - https://conda.anaconda.org/conda-forge
default_python: 3.7
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env})
envs_dirs:
  - C:\Users\jewell\Anaconda3\envs
  - C:\Users\jewell\.conda\envs
  - C:\Users\jewell\AppData\Local\conda\conda\envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - C:\Users\jewell\Anaconda3\pkgs
  - C:\Users\jewell\.conda\pkgs
  - C:\Users\jewell\AppData\Local\conda\conda\pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: C:\Users\jewell\Anaconda3
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: None
solver_ignore_timestamps: False
ssl_verify: True
subdir: win-64
subdirs:
  - win-64
  - noarch
target_prefix_override:
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []
```

</details>

**Comment by jorisvandenbossche** [comment]
@AlexJew thanks for the report (can you copy over the additional information from https://github.com/geopandas/geopandas/issues/1394 here?). 
That's a strange issue (conda-forge channel seems to be added correctly and strict channel priority in set in your configuration). Can you try if creating a new environment and installing geopandas in one go works? (`conda create -n test_env geopandas`)

**Comment by AlexJew** [comment]
Here's what I obtain when trying to create a new environment and install `geopandas`
```
(base) C:\Users\jewell>conda create -n test_env geopandas
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by AlexJew** [comment]
And, not sure if it helps, but here are the results for the same command, but with `verbosity: 3`. It is a lot of info ^^
```
(base) C:\Users\jewell>conda create -n test_env geopandas
DEBUG conda.gateways.logging:set_verbosity(231): verbosity set to 3
DEBUG conda.core.solve:solve_final_state(223): solving prefix C:\Users\jewell\Anaconda3\envs\test_env
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("geopandas")})
  prune: <auxlib._Null object at 0x0000019CE940DC48>
Collecting package metadata (current_repodata.json): ...working... TRACE conda.gateways.disk.test:file_path_is_writable(25): checking path is writable C:\Users\jewell\Anaconda3\pkgs\urls.txt
DEBUG conda.core.package_cache_data:_check_writable(259): package cache directory 'C:\Users\jewell\Anaconda3\pkgs' writable: True
DEBUG conda.core.subdir_data:_load(235): Using cached repodata for https://conda.anaconda.org/conda-forge/win-64/current_repodata.json at C:\Users\jewell\Anaconda3\pkgs\cache\f7597cf7.json. Timeout in 6 sec
DEBUG conda.core.subdir_data:_load(235): Using cached repodata for https://conda.anaconda.org/conda-forge/noarch/current_repodata.json at C:\Users\jewell\Anaconda3\pkgs\cache\62c98390.json. Timeout in 5 sec
DEBUG conda.core.subdir_data:_read_pickled(324): found pickle file C:\Users\jewell\Anaconda3\pkgs\cache\f7597cf7.q
DEBUG conda.core.subdir_data:_read_pickled(324): found pickle file C:\Users\jewell\Anaconda3\pkgs\cache\62c98390.q
done
Solving environment: ...working... DEBUG conda.resolve:get_reduced_index(572): Retrieving packages for:
  - geopandas
DEBUG conda.resolve:filter_group(633): attrs: pruned from 6 -> 3
DEBUG conda.resolve:filter_group(633): python: pruned from 27 -> 12
DEBUG conda.resolve:filter_group(633): pip: pruned from 9 -> 7
DEBUG conda.resolve:filter_group(633): python: pruned from 12 -> 9
DEBUG conda.resolve:filter_group(633): python_abi: pruned from 8 -> 6
DEBUG conda.resolve:filter_group(633): wincertstore: pruned from 19 -> 9
DEBUG conda.resolve:filter_group(633): wheel: pruned from 5 -> 4
DEBUG conda.resolve:filter_group(633): click-plugins: pruned from 5 -> 2
DEBUG conda.resolve:filter_group(633): click: pruned from 7 -> 5
DEBUG conda.resolve:filter_group(633): cligj: pruned from 5 -> 1
DEBUG conda.resolve:filter_group(633): gdal: pruned from 66 -> 30
DEBUG conda.resolve:filter_group(633): libgdal: pruned from 10 -> 0
DEBUG conda.resolve:filter_group(633): geopandas: pruned from 4 -> 2
DEBUG conda.resolve:filter_group(633): fiona: pruned from 3 -> 0
DEBUG conda.core.solve:_add_specs(617): specs_map with targets: OrderedDict()
DEBUG conda.resolve:bad_installed(1114): Checking if the current environment is consistent
DEBUG conda.core.solve:_find_inconsistent_packages(484): inconsistent precs: None
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 2
DEBUG conda.resolve:_get_sat_solver_cls(60): Using SAT solver interface 'pycosat'.
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 2849
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 2849
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 2850
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 19208
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 19208
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 19209
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 19208
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 19209
DEBUG conda.core.solve:_run_sat(757): conflicting specs:
  - geopandas
DEBUG conda.core.solve:_run_sat(801): final specs to add:
  - geopandas
DEBUG conda.resolve:solve(1246): Solving for:
  - 0: geopandas target=None optional=False
DEBUG conda.resolve:solve(1256): Solve: Getting reduced index of compliant packages
DEBUG conda.resolve:solve(1285): Solve: determining satisfiability
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 2849
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 2849
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 2850
failed with repodata from current_repodata.json, will retry with next repodata source.
DEBUG conda.core.solve:solve_final_state(223): solving prefix C:\Users\jewell\Anaconda3\envs\test_env
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec("geopandas")})
  prune: <auxlib._Null object at 0x0000019CE940DC48>
Collecting package metadata (repodata.json): ...working... DEBUG conda.core.subdir_data:_load(235): Using cached repodata for https://conda.anaconda.org/conda-forge/win-64/repodata.json at C:\Users\jewell\Anaconda3\pkgs\cache\5afe41e9.json. Timeout in 32 sec
DEBUG conda.core.subdir_data:_load(235): Using cached repodata for https://conda.anaconda.org/conda-forge/noarch/repodata.json at C:\Users\jewell\Anaconda3\pkgs\cache\09cdf8bf.json. Timeout in 29 sec
DEBUG conda.core.subdir_data:_read_pickled(324): found pickle file C:\Users\jewell\Anaconda3\pkgs\cache\5afe41e9.q
DEBUG conda.core.subdir_data:_read_pickled(324): found pickle file C:\Users\jewell\Anaconda3\pkgs\cache\09cdf8bf.q
done
Solving environment: ...working... DEBUG conda.resolve:get_reduced_index(572): Retrieving packages for:
  - geopandas
DEBUG conda.resolve:filter_group(633): geopandas: pruned from 43 -> 21
DEBUG conda.resolve:filter_group(633): fiona: pruned from 178 -> 33
DEBUG conda.resolve:filter_group(633): python: pruned from 104 -> 79
DEBUG conda.resolve:filter_group(633): pip: pruned from 79 -> 53
DEBUG conda.resolve:filter_group(633): setuptools: pruned from 285 -> 169
DEBUG conda.resolve:filter_group(633): wheel: pruned from 65 -> 45
DEBUG conda.resolve:filter_group(633): cligj: pruned from 6 -> 4
DEBUG conda.resolve:filter_group(633): click: pruned from 15 -> 10
DEBUG conda.resolve:filter_group(633): libgdal: pruned from 35 -> 0
DEBUG conda.resolve:filter_group(633): geopandas: pruned from 21 -> 19
DEBUG conda.resolve:filter_group(633): fiona: pruned from 33 -> 15
DEBUG conda.resolve:filter_group(633): click-plugins: pruned from 7 -> 5
DEBUG conda.resolve:filter_group(633): gdal: pruned from 91 -> 0
DEBUG conda.core.solve:_add_specs(617): specs_map with targets: OrderedDict()
DEBUG conda.resolve:bad_installed(1114): Checking if the current environment is consistent
DEBUG conda.core.solve:_find_inconsistent_packages(484): inconsistent precs: None
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 14061
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 14061
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 14062
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 159690
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 159690
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 159691
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 159690
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 159691
DEBUG conda.core.solve:_run_sat(757): conflicting specs:
  - geopandas
DEBUG conda.core.solve:_run_sat(801): final specs to add:
  - geopandas
DEBUG conda.resolve:solve(1246): Solving for:
  - 0: geopandas target=None optional=False
DEBUG conda.resolve:solve(1256): Solve: Getting reduced index of compliant packages
DEBUG conda.resolve:solve(1285): Solve: determining satisfiability
DEBUG conda.resolve:gen_clauses(914): gen_clauses returning with clause count: 14061
DEBUG conda.resolve:generate_spec_constraints(922): generate_spec_constraints returning with clause count: 14061
DEBUG conda.common._logic:_run_sat(601): Invoking SAT with clause count: 14062

Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Traceback (most recent call last):
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 37, in execute
    install(args, parser, 'create')
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\cli\install.py", line 292, in install
    raise e
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\core\solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\core\solve.py", line 808, in _run_sat
    should_retry_solve=ssc.should_retry_solve
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\resolve.py", line 1318, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "C:\Users\jewell\Anaconda3\lib\site-packages\conda\resolve.py", line 351, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError:
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by jorisvandenbossche** [comment]
@AlexJew Thanks for the additional info! 
I don't have a windows, so I can't try to reproduce. And I also don't directly notice something in the verbose logs .. (cc @ocefpaf)

**Comment by ocefpaf** [comment]
@AlexJew sorry for the delay to answer but I've been a bit swamped lately. I tested with both `strict` enabled and disabled and both worked. I guess that whatever the conflict was it got fixed while you waited for an answer here :-)

Please reopen if you are still experiencing this.
